// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc949.EnhanceRobot.subsystems;

import org.usfirst.frc949.EnhanceRobot.RobotMap;
import org.usfirst.frc949.EnhanceRobot.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController speedController1 = RobotMap.driveTrainSpeedController1;
    SpeedController speedController2 = RobotMap.driveTrainSpeedController2;
    SpeedController speedController3 = RobotMap.driveTrainSpeedController3;
    SpeedController speedController4 = RobotMap.driveTrainSpeedController4;
    RobotDrive mechanumDrive = RobotMap.driveTrainMechanumDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new DriveWithJoystickSpin());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public void setSpeed(double x, double y, double rotation, double gyroAngle) {
    	mechanumDrive.mecanumDrive_Cartesian(x, y, rotation, gyroAngle);
    }
}

